- Bumped version to v0.1.5.12 - Hopefully fixed the NoSuchMethodError associated to entity tasks, accessor methods and carpet build system - Changed an internal implementation to adapt to new reflection behavior - Fixed the issue that calmITTCrasher defaults to true - flippinCactus no longer allows survival players to rotate rails blocks. > If a rail configuration requires advanced rail mechanics to make, go learn them. If a rail configuration requires an update suppressor to make, go build one. Avoiding contraptions with a widely used carpet rule is against the spirits of TMC.